# Generated by Django 3.2.5 on 2021-07-16 21:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0006_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('figcaptionblock', wagtail.core.blocks.StructBlock([('figure', wagtail.images.blocks.ImageChooserBlock(label='Картинка')), ('caption', wagtail.core.blocks.CharBlock())])), ('rtfblock', wagtail.core.blocks.RichTextBlock(features=['h1', 'h6', 'hr', 'bold', 'italic'], help_text='Введите описание', label='Текст')), ('imgblock', wagtail.images.blocks.ImageChooserBlock(template='blocks/imgblock.html')), ('youtubeblock', wagtail.embeds.blocks.EmbedBlock(icon='success'))], blank=True),
        ),
    ]
