# Generated by Django 3.2.5 on 2021-08-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футеры'},
        ),
    ]
